Clean up getHomeHieFile and remove a delay from test
This test needed a 10s delay to avoid failing with:

    Exception: /home/runner/.cache/ghcide/a-1.0.0-inplace-88c1d56913b5839326e1d493406039cf083022bd/A.hie: openBinaryFile: does not exist (No such file or directory)
1606

The problem is that the getHomeHieFile didn't wait long enough for the hie file
to be refreshed.

I made a few more changes:

1. For non FOIs, avoid calling the GetParsedModule rule and use ghcSessionDeps
2. For FOIs, use the GetHieAst rule